{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/creation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/creation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.kasprasolutions.Creation\/documentation\/Creation","interfaceLanguage":"swift"},"topicSections":[{"title":"Protocols","identifiers":["doc:\/\/com.kasprasolutions.Creation\/documentation\/Creation\/NameGenerator","doc:\/\/com.kasprasolutions.Creation\/documentation\/Creation\/SlothGenerator"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"Creation","title":"Creation","symbolKind":"module","role":"collection","modules":[{"name":"Creation"}]},"hierarchy":{"paths":[[]]},"references":{"doc://com.kasprasolutions.Creation/documentation/Creation/CreationVersionString":{"role":"symbol","title":"CreationVersionString","fragments":[{"kind":"identifier","text":"CreationVersionString"}],"abstract":[{"type":"text","text":"Project version string for Creation."}],"identifier":"doc:\/\/com.kasprasolutions.Creation\/documentation\/Creation\/CreationVersionString","kind":"symbol","type":"topic","url":"\/documentation\/creation\/creationversionstring"},"doc://com.kasprasolutions.Creation/documentation/Creation/NameGenerator":{"role":"symbol","title":"NameGenerator","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NameGenerator"}],"abstract":[{"type":"text","text":"A type that generates names for sloths."}],"identifier":"doc:\/\/com.kasprasolutions.Creation\/documentation\/Creation\/NameGenerator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NameGenerator"}],"url":"\/documentation\/creation\/namegenerator"},"doc://com.kasprasolutions.Creation/documentation/Creation":{"role":"collection","title":"Creation","abstract":[],"identifier":"doc:\/\/com.kasprasolutions.Creation\/documentation\/Creation","kind":"symbol","type":"topic","url":"\/documentation\/creation"},"doc://com.kasprasolutions.Creation/documentation/Creation/CreationVersionNumber":{"role":"symbol","title":"CreationVersionNumber","fragments":[{"kind":"identifier","text":"CreationVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for Creation."}],"identifier":"doc:\/\/com.kasprasolutions.Creation\/documentation\/Creation\/CreationVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/creation\/creationversionnumber"},"doc://com.kasprasolutions.Creation/documentation/Creation/SlothGenerator":{"role":"symbol","title":"SlothGenerator","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SlothGenerator"}],"abstract":[{"type":"text","text":"A type that generates sloths."}],"identifier":"doc:\/\/com.kasprasolutions.Creation\/documentation\/Creation\/SlothGenerator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SlothGenerator"}],"url":"\/documentation\/creation\/slothgenerator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/com.kasprasolutions.Creation\/documentation\/Creation\/CreationVersionNumber","doc:\/\/com.kasprasolutions.Creation\/documentation\/Creation\/CreationVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}